accounts/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.signup, name='signup'),
    path('login', views.userLogin, name='login'),
    path('logout', views.userLogout, name='logout'),
    path('home', views.home, name='home'),
    path('playlist', views.createPlaylist, name='create_playlist'),
]

main/urls.py

from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('follow/<int:pk>', views.followSystem, name="followSystem"),
    path('like/<int:pk>', views.likeSystem, name="likeSystem"),
]

moonziky/urls.py
from django.contrib import admin
from django.urls import path, include
from django import views

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    #path('', include("main.urls")),
]

playlist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('dashboard', include('main.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
Users=get_user_model()

class UserFollowing(models.Model):
    user_id = models.ForeignKey(Users, related_name="following", on_delete=models.PROTECT)
    following_user_id = models.ForeignKey(Users, related_name="followers", on_delete=models.PROTECT)

main/models.py
from django.db import models
from django.contrib.auth import get_user_model
Users=get_user_model()


class playlist(models.Model):
    createdBy = models.ForeignKey(Users, on_delete=models.PROTECT)
    nameOfPlaylist = models.CharField(max_length=30)
    def __str__(self):
        return self.nameOfPlaylist

class playlistlink(models.Model):
    relatedPlaylist = models.ForeignKey('playlist', on_delete=models.PROTECT)
    linkOfPlaylist = models.URLField()
    def __str__(self):
        return self.linkOfPlaylist

class favplyalist(models.Model):
    likedPlaylist = models.ForeignKey('playlist', on_delete=models.CASCADE)
    likedBy = models.ForeignKey(Users, on_delete=models.PROTECT)

accounts/views.py
from django.shortcuts import render, redirect
from .froms import signupForm, createPlaylistForm,createPlaylistLinkForm
from django.contrib.auth import login, authenticate, logout, get_user_model
from main.models import playlistlink,playlist

Users=get_user_model()

def home(request, *args, **kwargs):
    user = request.user
    form = createPlaylistLinkForm(request.POST or None)
    form.fields['relatedPlaylist'].queryset = playlist.objects.filter(createdBy = user)
    if request.method == 'POST' and form.is_valid():

        form.save()
    context = {'form':form}
    return render(request, 'accounts/welcome.html', context)

def createPlaylist(request):
    form = createPlaylistForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        instance = form.save(commit=False)
        currentUser = request.user
        instance.createdBy = currentUser
        instance.save()
    context = {'form':form}
    return render(request, 'accounts/create_playlist.html', context)

def signup(request):
    form = signupForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('accounts:login')
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)

def userLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        rawPassword = request.POST.get('password')
        user = authenticate(username=username, password=rawPassword)
        if user is not None:
            login(request, user)
            return redirect('accounts:home')
        else:
            print('Wrong Username or Pass')
    return render(request, 'accounts/login.html')

def userLogout(request):
    logout(request)
    return redirect('accounts:login')


main/views.py
from django.shortcuts import render
from .models import playlist,favplyalist
from accounts.models import UserFollowing
from django.http import HttpResponse

def dashboard(request):
    allPlaylists = playlist.objects.all()
    context = {'listOfPlaylists': allPlaylists}
    return render(request, 'main/dashboard.html', context)

def followSystem(request, pk):
    followCreator = playlist.objects.get(id = pk)
    if request.method == "POST":
        if followCreator.createdBy == request.user:
            #print(followCreator.createdBy)
            #print(request.user)
            return HttpResponse("You Cannot Follow Yourself")
        elif UserFollowing.objects.filter(user_id = followCreator.createdBy, following_user_id = request.user).exists():
            return HttpResponse("You Are Already Following This User")
        else:
            instance = UserFollowing(user_id = followCreator.createdBy, following_user_id = request.user)
            instance.save()
    context = {'Creator': followCreator.createdBy.username}
    return render(request, 'main/followPage.html', context)

def likeSystem(request, pk):
    getPlaylist = playlist.objects.get(id = pk)
    if request.method == 'POST':
        if favplyalist.objects.filter(likedPlaylist = getPlaylist, likedBy = request.user).exists():
            return HttpResponse('You have already Liked this Playlist')
        else:
            instance = favplyalist(likedPlaylist = getPlaylist, likedBy = request.user)
            instance.save()
    context = {'playlistName': getPlaylist}
    return render(request, 'main/likePage.html', context)

moonziky/main/views.py
from django.shortcuts import render
from .models import playlist,favplyalist
from accounts.models import UserFollowing
from django.http import HttpResponse

def dashboard(request):
    allPlaylists = playlist.objects.all()
    context = {'Lista de Playlists': allPlaylists}
    return render(request, 'main/dashboard.html', context)

def followSystem(request, pk):
    followCreator = playlist.objects.get(id = pk)
    if request.method == "POST":
        if followCreator.createdBy == request.user:
            #print(followCreator.createdBy)
            #print(request.user)
            return HttpResponse("Você não pode se seguir")
        elif UserFollowing.objects.filter(user_id = followCreator.createdBy, following_user_id = request.user).exists():
            return HttpResponse("Você já segue este usuário")
        else:
            instance = UserFollowing(user_id = followCreator.createdBy, following_user_id = request.user)
            instance.save()
    context = {'Criador': followCreator.createdBy.username}
    return render(request, 'main/followPage.html', context)

def likeSystem(request, pk):
    getPlaylist = playlist.objects.get(id = pk)
    if request.method == 'POST':
        if favplyalist.objects.filter(likedPlaylist = getPlaylist, likedBy = request.user).exists():
            return HttpResponse('Você já curtiu essa playlist')
        else:
            instance = favplyalist(likedPlaylist = getPlaylist, likedBy = request.user)
            instance.save()
    context = {'Nome da playlist': getPlaylist}
    return render(request, 'main/likePage.html', context)

accounts/templates/accounts/create_playlist.html
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>

accounts/templates/accounts/login.html
<form action="" method="post">
  
    {% csrf_token %}
  <input type="text" name="username">
  <input type="password" name="password">

<input type="submit" value="Login">
</form>
<strong>Not Have An Account?</strong><a href="{% url 'accounts:signup' %}">SignUp Here</a>

accounts/templates/accounts/signup.html
<form action="" method="post">
  
    {% csrf_token %}
  {{form.as_p}}
<input type="submit" value="Signup">
</form>
<strong>Already Have An Account</strong><a href="{% url 'accounts:login' %}">Login Here</a>

accounts/templates/accounts/welcome.html
<h2>Welcome {{ user.username }}</h2>

{% if user.is_authenticated %}
<h2>Create the Playlist <a href="{% url 'accounts:create_playlist' %}">here</a> Or go to the <a href="{% url 'main:dashboard' %}">Dashboard</a></h2>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save">
</form>
<a href="{% url 'accounts:logout' %}">Logout</a>
{% else %}
<a href="{% url 'accounts:login' %}">Login</a>
{% endif %}

main/templates/main/base.html
<html lang="en">
    <head>
        {% block title %}<title>Moonziky</title>{% endblock %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" 
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
        crossorigin="anonymous">
        <!-- Add additional CSS in static file -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>

    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                {% block sidebar %}
                    <ul class="sidebar-nav">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'playlist' %}">All Playlists</a></li>
                        <li><a href="">All Musics</a></li>
                    </ul>
                {% endblock %}
                </div>
                <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
            </div>
        </div>
    </body>
</html>

main/templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
  border-collapse: collapse;
        }
    </style>
</head>

<body>

    <table>
        <th>
            <tr>
                <th>Sr No</th>
                <th>Playlist Name</th>
                <th>Created By</th>
                <th>Action 1</th>
                <th>Action 2</th>
            </tr>
        </th>
        {% for list in listOfPlaylists %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{list.nameOfPlaylist}}</td>
            <td>{{list.createdBy}}</td>
            <td><a href="{% url 'main:followSystem' list.id %}">Follow </a>the creator</td>
            <td><a href="{% url 'main:likeSystem' list.id %}">Like</a> the Playlist</td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'accounts:logout' %}">Logout</a>
</body>

</html>

main/templates/main/followPage.html
<strong>Username: </strong><p>{{Creator}}</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="follow">
</form>

main/templates/main/home.html
{% extends 'main/base.html' %}

main/templates/main/index.html
{% extends "main/base.html" %}

{% block content %}
  <h1>Moonziky Home</h1>
  <p>Welcome to Moonziky!</p>
  <h2>Dynamic content</h2>
  <p>The Moonziky has the following record counts:</p>
  <ul>
    <li><strong>Playlist:</strong> {{ numPlaylist }}</li>
    <li><strong>Musics:</strong> {{ numMusic }}</li>
  </ul>
{% endblock %}

main/templates/main/likePage.html
<strong>Playlist Name: </strong><p>{{playlistName}}</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Like">
</form>

main/templates/main/login.html
<form action="/login/" method="POST">
    
    <div class="container">
      <label for="uname"><b>Nome do usuario</b></label>
      <input type="text" placeholder="Informe o nome do usuario" name="uname" required>
  
      <label for="psw"><b>Senha</b></label>
      <input type="password" placeholder="Informe a senha" name="password" required>
  
      <button type="submit">Login</button>
      <label>
        <input type="checkbox" checked="checked" name="remember"> Lembrar-me
      </label>
    </div>
  
    <div class="container" style="background-color:#f1f1f1">
      <button type="button" class="cancelbtn">Cancelar</button>
      <span class="psw">Esqueceu <a href="#">a senha?</a></span>
    </div>
  </form>

main/templates/main/playlist.html
<h1>Essa é a Playlist: {{ playlistName }}!</h1>

main/templates/main/playlist_detail.html
{% extends "main/base.html" %}

{% block content %}
    <h1>Title: {{ playlist.name }}</h1>

    <p><strong>Nome:</strong> <a href="">{{ playlist.name }}</a></p>
    {% comment %} <p><strong>Author:</strong> <a href="">{{ playlist.author }}</a></p>
    <p><strong>Summary:</strong> {{ playlist.summary }}</p>
    <p><strong>ISBN:</strong> {{ playlist.isbn }}</p>
    <p><strong>Language:</strong> {{ playlist.language }}</p>
    <p><strong>Genre:</strong> {% for genre in playlist.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p> {% endcomment %}

{% endblock %}

main/templates/main/playlist_list.html
{% extends "main/base.html" %}

{% block content %}
    <h1>Playlists</h1>
    {% if playlist_list %}
    <ul>
        {% for playlist in playlist_list %}
            <li>
                <a href="{{ playlist.get_absolute_url }}">{{ playlist.name }}</a> ({{playlist.musics.count}})

            </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>There are no playlist in the Playlists.</p>

    {% endif %}

{% endblock %}

main/templates/main/register.html
<form action="/cadastrar/" method="POST">
    <div class="container">
      <h1>Cadastro</h1>
      <p>Preencha o cadastro para entrar.</p>
      <hr>
  
      <label for="email"><b>Email</b></label>
      <input type="text" placeholder="informe o Email" name="email" id="email" required>
  
      <label for="psw"><b>Senha</b></label>
      <input type="password" placeholder="Informe a senha" name="password" id="psw" required>
  
      <hr>
  
      <button type="submit" class="registerbtn">Cadastrar</button>
    </div>
  
    <div class="container signin">
    </div>
  </form>

moonziky/main/templates/main/dashboard.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-3">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        table,
        th,
        td {
            border: 1px solid black;
  border-collapse: collapse;
        }
    </style>
</head>

<body>

    <table>
        <th>
            <tr>
                <th>Sr No</th>
                <th>Nome da Playlist</th>
                <th>Criado por:</th>
                <th>Ação 1</th>
                <th>Ação 2</th>
            </tr>
        </th>
        {% for list in listOfPlaylists %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>{{list.nameOfPlaylist}}</td>
            <td>{{list.createdBy}}</td>
            <td><a href="{% url 'main:followSystem' list.id %}">Seguir </a>o criador</td>
            <td><a href="{% url 'main:likeSystem' list.id %}">Curtir</a>a Playlist</td>
        </tr>
        {% endfor %}
    </table>
    <a href="{% url 'accounts:logout' %}">Logout</a>
</body>

</html>

moonziky/main/templates/main/followPage.html
<strong>Usuario: </strong><p>{{Creator}}</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="enviar" value="seguir">
</form>

moonziky/main/templates/main/likePage.html
<strong>Nome da Playlist: </strong><p>{{playlistName}}</p>
<form action="" method="post">
    {% csrf_token %}
    <input type="enviar" value="curtir">
</form>